{{- if .Values.ingress.enabled -}}
{{- $apiHost := .Values.ingress.api.host -}}
{{- $dashboardHost := .Values.ingress.dashboard.host -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "featuresignals.fullname" . }}-ingress
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "featuresignals.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "caddy" | quote }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  rules:
    - host: {{ $apiHost | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.api.path | default "/" }}
            pathType: {{ .Values.ingress.api.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "featuresignals.fullname" . }}-server
                port:
                  number: {{ .Values.service.server.port | default 8080 }}
    - host: {{ $dashboardHost | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.dashboard.path | default "/" }}
            pathType: {{ .Values.ingress.dashboard.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "featuresignals.fullname" . }}-dashboard
                port:
                  number: {{ .Values.service.dashboard.port | default 3000 }}
{{- end }}
