package iac

import (
	"bytes"
	"context"
	"fmt"
	"text/template"
)

// AnsibleGenerator generates Ansible playbook YAML files from the common
// ResourceModel. It produces a playbook.yml with FeatureSignals module calls
// and group_vars configuration.
type AnsibleGenerator struct {
	templates *template.Template
}

// NewAnsibleGenerator creates a new AnsibleGenerator with pre-loaded templates.
func NewAnsibleGenerator() *AnsibleGenerator {
	funcMap := template.FuncMap{
		"quote":    func(s string) string { return fmt.Sprintf("%q", s) },
		"boolStr":  func(b bool) string { return fmt.Sprintf("%v", b) },
		"indent":   func(n int, s string) string { return indent(s, n) },
		"toSnake":  toSnakeCase,
		"ansibleVar": ansibleSanitize,
		"quoteList": quoteList,
	}
	tmpl := template.Must(template.New("ansible").Funcs(funcMap).Parse(ansiblePlaybookTmpl + ansibleVarsTmpl))
	return &AnsibleGenerator{templates: tmpl}
}

// Name returns the generator name.
func (g *AnsibleGenerator) Name() string { return "ansible" }

// FileExtension returns the file extension for generated files.
func (g *AnsibleGenerator) FileExtension() string { return ".yml" }

// Generate produces Ansible playbook YAML files from the resource model.
func (g *AnsibleGenerator) Generate(ctx context.Context, model ResourceModel) ([]GeneratedFile, error) {
	var files []GeneratedFile

	var playbookBuf bytes.Buffer
	if err := g.templates.ExecuteTemplate(&playbookBuf, "playbook.yml", model); err != nil {
		return nil, fmt.Errorf("ansible playbook template: %w", err)
	}
	files = append(files, GeneratedFile{
		Path:    "playbook.yml",
		Content: playbookBuf.Bytes(),
		Comment: "Ansible playbook for FeatureSignals resource management",
	})

	var varsBuf bytes.Buffer
	if err := g.templates.ExecuteTemplate(&varsBuf, "vars.yml", model); err != nil {
		return nil, fmt.Errorf("ansible vars template: %w", err)
	}
	files = append(files, GeneratedFile{
		Path:    "group_vars/all.yml",
		Content: varsBuf.Bytes(),
		Comment: "Ansible variables for FeatureSignals configuration",
	})

	return files, nil
}

// ─── Templates ──────────────────────────────────────────────────────────────

const ansiblePlaybookTmpl = `# Generated by FeatureSignals IaC Generator
# Ansible playbook for FeatureSignals resource management
---
- name: Manage FeatureSignals resources
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Ensure FeatureSignals API connectivity
      uri:
        url: "{{ fs_host | default('https://api.featuresignals.com') }}/health"
        method: GET
        headers:
          Authorization: "ApiKey {{ fs_api_key }}"
        status_code: 200
      register: fs_health
      changed_when: false

    - name: Display connection status
      debug:
        msg: "Connected to FeatureSignals API at {{ fs_host | default('https://api.featuresignals.com') }}"
      when: fs_health.status == 200

{{- if .Projects }}

    # ─── Projects ─────────────────────────────────────────────────────────────
    {{- range .Projects }}

    - name: "Ensure project {{ .Name }}"
      fs_project:
        state: present
        api_key: "{{ '{{ fs_api_key }}' }}"
        host: "{{ '{{ fs_host | default(\"https://api.featuresignals.com\") }}' }}"
        name: {{ .Name | quote }}
        {{- if .Slug }}
        slug: {{ .Slug | quote }}
        {{- end }}
        {{- if .Description }}
        description: {{ .Description | quote }}
        {{- end }}
      register: fs_project_{{ .Slug | ansibleVar }}
    {{- end }}
{{- end }}

{{- if .Environments }}

    # ─── Environments ─────────────────────────────────────────────────────────
    {{- range .Environments }}

    - name: "Ensure environment {{ .Name }}"
      fs_environment:
        state: present
        api_key: "{{ '{{ fs_api_key }}' }}"
        host: "{{ '{{ fs_host | default(\"https://api.featuresignals.com\") }}' }}"
        project_slug: {{ .ProjectSlug | quote }}
        name: {{ .Name | quote }}
        {{- if .Slug }}
        slug: {{ .Slug | quote }}
        {{- end }}
        {{- if .Color }}
        color: {{ .Color | quote }}
        {{- end }}
      register: fs_env_{{ .Slug | ansibleVar }}
    {{- end }}
{{- end }}

{{- if .Flags }}

    # ─── Feature Flags ────────────────────────────────────────────────────────
    {{- range .Flags }}

    - name: "Ensure flag {{ .Name }}"
      fs_flag:
        state: present
        api_key: "{{ '{{ fs_api_key }}' }}"
        host: "{{ '{{ fs_host | default(\"https://api.featuresignals.com\") }}' }}"
        project_slug: {{ .ProjectSlug | quote }}
        key: {{ .Key | quote }}
        name: {{ .Name | quote }}
        {{- if .Description }}
        description: {{ .Description | quote }}
        {{- end }}
        flag_type: {{ .FlagType | quote }}
        default_value: {{ .DefaultValue | quote }}
        {{- if .Tags }}
        tags: [{{ range $i, $tag := .Tags }}{{ if $i }}, {{ end }}{{ $tag | quote }}{{ end }}]
        {{- end }}
        {{- if .Environments }}
        environments:
          {{- range .Environments }}
          - key: {{ .Key | quote }}
            enabled: {{ .Enabled | boolStr }}
          {{- end }}
        {{- end }}
      register: fs_flag_{{ .Key | ansibleVar }}
    {{- end }}
{{- end }}

{{- if .Segments }}

    # ─── Segments ─────────────────────────────────────────────────────────────
    {{- range .Segments }}

    - name: "Ensure segment {{ .Name }}"
      fs_segment:
        state: present
        api_key: "{{ '{{ fs_api_key }}' }}"
        host: "{{ '{{ fs_host | default(\"https://api.featuresignals.com\") }}' }}"
        project_slug: {{ .ProjectSlug | quote }}
        key: {{ .Key | quote }}
        name: {{ .Name | quote }}
        match_type: {{ .MatchType | quote }}
        {{- if .Rules }}
        rules:
          {{- range .Rules }}
          - attribute: {{ .Attribute | quote }}
            operator: {{ .Operator | quote }}
            values: [{{ range $i, $v := .Values }}{{ if $i }}, {{ end }}{{ $v | quote }}{{ end }}]
          {{- end }}
        {{- end }}
      register: fs_segment_{{ .Key | ansibleVar }}
    {{- end }}
{{- end }}

{{- if .Webhooks }}

    # ─── Webhooks ─────────────────────────────────────────────────────────────
    {{- range .Webhooks }}

    - name: "Ensure webhook {{ .Name }}"
      fs_webhook:
        state: present
        api_key: "{{ '{{ fs_api_key }}' }}"
        host: "{{ '{{ fs_host | default(\"https://api.featuresignals.com\") }}' }}"
        project_slug: {{ .ProjectSlug | quote }}
        name: {{ .Name | quote }}
        url: {{ .URL | quote }}
        enabled: {{ .Enabled | boolStr }}
        event_types: [{{ range $i, $e := .EventTypes }}{{ if $i }}, {{ end }}{{ $e | quote }}{{ end }}]
      register: fs_webhook_{{ .Name | ansibleVar }}
    {{- end }}
{{- end }}

    - name: Display summary
      debug:
        msg: "FeatureSignals resources configured successfully"
`

const ansibleVarsTmpl = `# FeatureSignals Ansible variables
# Generated by FeatureSignals IaC Generator
---
# Required: FeatureSignals API key
# fs_api_key: "your-api-key-here"

# Optional: API host URL (defaults to https://api.featuresignals.com)
# fs_host: "https://api.featuresignals.com"

# Resource configuration
fs_config:
{{- if .Projects }}
  projects:
    {{- range .Projects }}
    - name: {{ .Name | quote }}
      {{- if .Slug }}
      slug: {{ .Slug | quote }}
      {{- end }}
      {{- if .Description }}
      description: {{ .Description | quote }}
      {{- end }}
    {{- end }}
{{- end }}

{{- if .Environments }}
  environments:
    {{- range .Environments }}
    - project_slug: {{ .ProjectSlug | quote }}
      name: {{ .Name | quote }}
      {{- if .Slug }}
      slug: {{ .Slug | quote }}
      {{- end }}
      {{- if .Color }}
      color: {{ .Color | quote }}
      {{- end }}
    {{- end }}
{{- end }}

{{- if .Flags }}
  flags:
    {{- range .Flags }}
    - project_slug: {{ .ProjectSlug | quote }}
      key: {{ .Key | quote }}
      name: {{ .Name | quote }}
      flag_type: {{ .FlagType | quote }}
      default_value: {{ .DefaultValue | quote }}
      {{- if .Tags }}
      tags: [{{ range $i, $tag := .Tags }}{{ if $i }}, {{ end }}{{ $tag | quote }}{{ end }}]
      {{- end }}
    {{- end }}
{{- end }}
`
