package iac

import (
	"bytes"
	"context"
	"fmt"
	"strings"
	"text/template"
)

// PulumiGenerator generates Pulumi TypeScript configuration files from the
// common ResourceModel. It produces index.ts and config.ts files that can
// be used with the @featuresignals/pulumi Pulumi provider.
type PulumiGenerator struct {
	templates *template.Template
}

// NewPulumiGenerator creates a new PulumiGenerator with pre-loaded templates.
func NewPulumiGenerator() *PulumiGenerator {
	funcMap := template.FuncMap{
		"pascalCase":   pulumiResourceName,
		"quote":        func(s string) string { return fmt.Sprintf("%q", s) },
		"indent":       func(n int, s string) string { return indent(s, n) },
		"toCamelCase":  toCamelCase,
		"boolStr":      func(b bool) string { return fmt.Sprintf("%v", b) },
		"pulumiSafeKey": func(s string) string {
			r := strings.NewReplacer("-", "_", ".", "_", " ", "_")
			return r.Replace(s)
		},
	}
	tmpl := template.Must(template.New("pulumi").Funcs(funcMap).Parse(pulumiIndexTmpl + pulumiConfigTmpl))
	return &PulumiGenerator{templates: tmpl}
}

// Name returns the generator name.
func (g *PulumiGenerator) Name() string { return "pulumi" }

// FileExtension returns the file extension for generated files.
func (g *PulumiGenerator) FileExtension() string { return ".ts" }

// Generate produces Pulumi TypeScript configuration files from the resource model.
func (g *PulumiGenerator) Generate(ctx context.Context, model ResourceModel) ([]GeneratedFile, error) {
	var files []GeneratedFile

	var indexBuf bytes.Buffer
	if err := g.templates.ExecuteTemplate(&indexBuf, "index.ts", model); err != nil {
		return nil, fmt.Errorf("pulumi index template: %w", err)
	}
	files = append(files, GeneratedFile{
		Path:    "index.ts",
		Content: indexBuf.Bytes(),
		Comment: "Pulumi program for FeatureSignals resources",
	})

	var configBuf bytes.Buffer
	if err := g.templates.ExecuteTemplate(&configBuf, "config.ts", model); err != nil {
		return nil, fmt.Errorf("pulumi config template: %w", err)
	}
	files = append(files, GeneratedFile{
		Path:    "config.ts",
		Content: configBuf.Bytes(),
		Comment: "Pulumi configuration and stack references",
	})

	return files, nil
}

// ─── Templates ──────────────────────────────────────────────────────────────

const pulumiIndexTmpl = `// Generated by FeatureSignals IaC Generator
// Pulumi TypeScript program for FeatureSignals resources
import * as fs from "@featuresignals/pulumi";
import { Config } from "@pulumi/pulumi";

const config = new Config("featuresignals");
const apiKey = config.requireSecret("apiKey");
const host = config.get("host") || "https://api.featuresignals.com";

{{- if .Projects }}

// ─── Projects ─────────────────────────────────────────────────────────────────
{{- range .Projects }}

const {{ .Slug | pulumiSafeKey }} = new fs.Project("{{ .Slug | pulumiSafeKey }}", {
    name: {{ .Name | quote }},
    {{- if .Slug }}
    slug: {{ .Slug | quote }},
    {{- end }}
    {{- if .Description }}
    description: {{ .Description | quote }},
    {{- end }}
});
{{- end }}
{{- end }}

{{- if .Environments }}

// ─── Environments ─────────────────────────────────────────────────────────────
{{- range .Environments }}

const {{ .Slug | pulumiSafeKey }} = new fs.Environment("{{ .Slug | pulumiSafeKey }}", {
    projectSlug: {{ .ProjectSlug | quote }},
    name: {{ .Name | quote }},
    {{- if .Slug }}
    slug: {{ .Slug | quote }},
    {{- end }}
    {{- if .Color }}
    color: {{ .Color | quote }},
    {{- end }}
});
{{- end }}
{{- end }}

{{- if .Flags }}

// ─── Feature Flags ────────────────────────────────────────────────────────────
{{- range .Flags }}

const {{ .Key | pulumiSafeKey }} = new fs.Flag("{{ .Key | pulumiSafeKey }}", {
    projectSlug: {{ .ProjectSlug | quote }},
    key: {{ .Key | quote }},
    name: {{ .Name | quote }},
    {{- if .Description }}
    description: {{ .Description | quote }},
    {{- end }}
    flagType: {{ .FlagType | quote }},
    defaultValue: {{ .DefaultValue | quote }},
    {{- if .Tags }}
    tags: [{{ range $i, $tag := .Tags }}{{ if $i }}, {{ end }}{{ $tag | quote }}{{ end }}],
    {{- end }}
    {{- if .Environments }}
    environments: [
        {{- range .Environments }}
        { key: {{ .Key | quote }}, enabled: {{ .Enabled | boolStr }} },
        {{- end }}
    ],
    {{- end }}
});
{{- end }}
{{- end }}

{{- if .Segments }}

// ─── Segments ─────────────────────────────────────────────────────────────────
{{- range .Segments }}

const {{ .Key | pulumiSafeKey }} = new fs.Segment("{{ .Key | pulumiSafeKey }}", {
    projectSlug: {{ .ProjectSlug | quote }},
    key: {{ .Key | quote }},
    name: {{ .Name | quote }},
    matchType: {{ .MatchType | quote }},
    {{- if .Rules }}
    rules: [
        {{- range .Rules }}
        { attribute: {{ .Attribute | quote }}, operator: {{ .Operator | quote }}, values: [{{ range $i, $v := .Values }}{{ if $i }}, {{ end }}{{ $v | quote }}{{ end }}] },
        {{- end }}
    ],
    {{- end }}
});
{{- end }}
{{- end }}

{{- if .Webhooks }}

// ─── Webhooks ─────────────────────────────────────────────────────────────────
{{- range .Webhooks }}

const {{ .Name | pulumiSafeKey }} = new fs.Webhook("{{ .Name | pulumiSafeKey }}", {
    projectSlug: {{ .ProjectSlug | quote }},
    name: {{ .Name | quote }},
    url: {{ .URL | quote }},
    enabled: {{ .Enabled | boolStr }},
    eventTypes: [{{ range $i, $e := .EventTypes }}{{ if $i }}, {{ end }}{{ $e | quote }}{{ end }}],
});
{{- end }}
{{- end }}

// ─── Exports ──────────────────────────────────────────────────────────────────
{{- if .Projects }}
export const projects = {
    {{- range .Projects }}
    {{ .Slug | pulumiSafeKey }},
    {{- end }}
};
{{- end }}

{{- if .Flags }}
export const flags = {
    {{- range .Flags }}
    {{ .Key | pulumiSafeKey }},
    {{- end }}
};
{{- end }}
`

const pulumiConfigTmpl = `// Pulumi configuration for FeatureSignals
// Generated by FeatureSignals IaC Generator
//
// Usage:
//   pulumi config set featuresignals:apiKey <your-api-key> --secret
//   pulumi config set featuresignals:host https://api.featuresignals.com

export interface FeatureSignalsConfig {
    apiKey: string;
    host?: string;
}

export const defaultConfig: FeatureSignalsConfig = {
    host: "https://api.featuresignals.com",
};
`

// toCamelCase converts a string to camelCase.
func toCamelCase(s string) string {
	if s == "" {
		return ""
	}
	pascal := pulumiResourceName(s)
	if len(pascal) > 0 {
		runes := []rune(pascal)
		runes[0] = unicodeToLower(runes[0])
		return string(runes)
	}
	return s
}

func unicodeToLower(r rune) rune {
	if r >= 'A' && r <= 'Z' {
		return r + 32
	}
	return r
}