package iac

import (
	"bytes"
	"context"
	"fmt"
	"strings"
	"text/template"
)

// TerraformGenerator generates Terraform HCL configuration files from the
// common ResourceModel. It produces provider.tf, main.tf, and variables.tf
// files that can be used with the FeatureSignals Terraform provider.
type TerraformGenerator struct {
	templates *template.Template
}

// NewTerraformGenerator creates a new TerraformGenerator with pre-loaded
// templates for generating HCL configuration.
func NewTerraformGenerator() *TerraformGenerator {
	funcMap := template.FuncMap{
		"toSnakeCase": toSnakeCase,
		"quote":       func(s string) string { return fmt.Sprintf("%q", s) },
		"indent":      func(n int, s string) string { return indent(s, n) },
		"terrformResourceName": func(s string) string {
			return strings.ReplaceAll(strings.ToLower(s), "-", "_")
		},
		"join": strings.Join,
	}
	tmpl := template.Must(template.New("terraform").Funcs(funcMap).Parse(terraformProviderTmpl + terraformMainTmpl + terraformVariablesTmpl))
	return &TerraformGenerator{templates: tmpl}
}

// Name returns the generator name.
func (g *TerraformGenerator) Name() string { return "terraform" }

// FileExtension returns the file extension for generated files.
func (g *TerraformGenerator) FileExtension() string { return ".tf" }

// Generate produces Terraform HCL configuration files from the resource model.
func (g *TerraformGenerator) Generate(ctx context.Context, model ResourceModel) ([]GeneratedFile, error) {
	var files []GeneratedFile

	// Provider file
	var providerBuf bytes.Buffer
	if err := g.templates.ExecuteTemplate(&providerBuf, "provider.tf", model); err != nil {
		return nil, fmt.Errorf("terraform provider template: %w", err)
	}
	files = append(files, GeneratedFile{
		Path:    "provider.tf",
		Content: providerBuf.Bytes(),
		Comment: "Terraform provider configuration for FeatureSignals",
	})

	// Main resources file
	var mainBuf bytes.Buffer
	if err := g.templates.ExecuteTemplate(&mainBuf, "main.tf", model); err != nil {
		return nil, fmt.Errorf("terraform main template: %w", err)
	}
	files = append(files, GeneratedFile{
		Path:    "main.tf",
		Content: mainBuf.Bytes(),
		Comment: "FeatureSignals resource definitions",
	})

	// Variables file
	var varsBuf bytes.Buffer
	if err := g.templates.ExecuteTemplate(&varsBuf, "variables.tf", model); err != nil {
		return nil, fmt.Errorf("terraform variables template: %w", err)
	}
	files = append(files, GeneratedFile{
		Path:    "variables.tf",
		Content: varsBuf.Bytes(),
		Comment: "Terraform input variables",
	})

	return files, nil
}

// ─── Templates ──────────────────────────────────────────────────────────────

const terraformProviderTmpl = `# Generated by FeatureSignals IaC Generator
# Terraform provider configuration
# Provider: featuresignals/featuresignals

terraform {
  required_providers {
    featuresignals = {
      source  = "featuresignals/featuresignals"
      version = "~> 1.0"
    }
  }
}

provider "featuresignals" {
  # Configure via environment variable FEATURESIGNALS_API_KEY
  # or set explicitly:
  # api_key = var.featuresignals_api_key
}
`

const terraformVariablesTmpl = `# Input variables for FeatureSignals Terraform configuration
# Generated by FeatureSignals IaC Generator

variable "featuresignals_api_key" {
  description = "API key for FeatureSignals authentication"
  type        = string
  sensitive   = true
}

variable "featuresignals_host" {
  description = "FeatureSignals API host URL"
  type        = string
  default     = "https://api.featuresignals.com"
}
`

const terraformMainTmpl = `# FeatureSignals resource definitions
# Generated by FeatureSignals IaC Generator

{{- if .Projects }}

# ─── Projects ─────────────────────────────────────────────────────────────────
{{- range .Projects }}

resource "featuresignals_project" "{{ .Slug | terrformResourceName }}" {
  name        = {{ .Name | quote }}
  {{- if .Slug }}
  slug        = {{ .Slug | quote }}
  {{- end }}
  {{- if .Description }}
  description = {{ .Description | quote }}
  {{- end }}
}
{{- end }}
{{- end }}

{{- if .Environments }}

# ─── Environments ─────────────────────────────────────────────────────────────
{{- range .Environments }}

resource "featuresignals_environment" "{{ .Slug | terrformResourceName }}" {
  project_slug = {{ .ProjectSlug | quote }}
  name         = {{ .Name | quote }}
  {{- if .Slug }}
  slug         = {{ .Slug | quote }}
  {{- end }}
  {{- if .Color }}
  color        = {{ .Color | quote }}
  {{- end }}
  {{- if .Description }}
  description  = {{ .Description | quote }}
  {{- end }}
}
{{- end }}
{{- end }}

{{- if .Flags }}

# ─── Feature Flags ────────────────────────────────────────────────────────────
{{- range .Flags }}

resource "featuresignals_flag" "{{ .Key | terrformResourceName }}" {
  project_slug  = {{ .ProjectSlug | quote }}
  key           = {{ .Key | quote }}
  name          = {{ .Name | quote }}
  {{- if .Description }}
  description   = {{ .Description | quote }}
  {{- end }}
  flag_type     = {{ .FlagType | quote }}
  default_value = {{ .DefaultValue | quote }}
  {{- if .Tags }}
  tags          = [{{ range $i, $tag := .Tags }}{{ if $i }}, {{ end }}{{ $tag | quote }}{{ end }}]
  {{- end }}
}
{{- end }}
{{- end }}

{{- if .Segments }}

# ─── Segments ─────────────────────────────────────────────────────────────────
{{- range .Segments }}

resource "featuresignals_segment" "{{ .Key | terrformResourceName }}" {
  project_slug = {{ .ProjectSlug | quote }}
  key          = {{ .Key | quote }}
  name         = {{ .Name | quote }}
  {{- if .Description }}
  description  = {{ .Description | quote }}
  {{- end }}
  match_type   = {{ .MatchType | quote }}
  {{- if .Rules }}
  rules = jsonencode([
    {{- range .Rules }}
    {
      attribute = {{ .Attribute | quote }}
      operator  = {{ .Operator | quote }}
      values    = [{{ range $i, $v := .Values }}{{ if $i }}, {{ end }}{{ $v | quote }}{{ end }}]
    },
    {{- end }}
  ])
  {{- end }}
}
{{- end }}
{{- end }}

{{- if .Webhooks }}

# ─── Webhooks ─────────────────────────────────────────────────────────────────
{{- range .Webhooks }}

resource "featuresignals_webhook" "{{ .Name | terrformResourceName }}" {
  project_slug = {{ .ProjectSlug | quote }}
  name         = {{ .Name | quote }}
  url          = {{ .URL | quote }}
  enabled      = {{ .Enabled }}
  event_types  = [{{ range $i, $e := .EventTypes }}{{ if $i }}, {{ end }}{{ $e | quote }}{{ end }}]
}
{{- end }}
{{- end }}

{{- if .APIKeys }}

# ─── API Keys ─────────────────────────────────────────────────────────────────
{{- range .APIKeys }}

resource "featuresignals_api_key" "{{ .Name | terrformResourceName }}" {
  environment_slug = {{ .EnvironmentSlug | quote }}
  name             = {{ .Name | quote }}
  key_type         = {{ .KeyType | quote }}
  {{- if .ExpiresAt }}
  expires_at       = {{ .ExpiresAt | quote }}
  {{- end }}
}
{{- end }}
{{- end }}

# Outputs
output "featuresignals_project_ids" {
  description = "IDs of created FeatureSignals projects"
  value = {
    {{- range .Projects }}
    {{ .Slug | terrformResourceName }} = featuresignals_project.{{ .Slug | terrformResourceName }}.id
    {{- end }}
  }
}

output "featuresignals_flag_keys" {
  description = "Keys of created FeatureSignals flags"
  value = {
    {{- range .Flags }}
    {{ .Key | terrformResourceName }} = featuresignals_flag.{{ .Key | terrformResourceName }}.key
    {{- end }}
  }
}
`
