import { vi } from "vitest";

export function createMockApi() {
  return {
    getPricing: vi.fn().mockResolvedValue({ plans: {}, common_features: [] }),
    login: vi.fn(),
    refresh: vi.fn(),
    sendVerificationEmail: vi.fn(),
    initiateSignup: vi.fn(),
    completeSignup: vi.fn(),
    resendSignupOTP: vi.fn(),
    submitSalesInquiry: vi.fn(),
    listProjects: vi.fn().mockResolvedValue({ data: [] }),
    createProject: vi.fn(),
    getProject: vi.fn(),
    deleteProject: vi.fn(),
    listEnvironments: vi.fn().mockResolvedValue({ data: [] }),
    createEnvironment: vi.fn(),
    deleteEnvironment: vi.fn(),
    listFlags: vi.fn().mockResolvedValue({ data: [] }),
    getFlag: vi.fn(),
    createFlag: vi.fn(),
    updateFlag: vi.fn(),
    deleteFlag: vi.fn(),
    getFlagState: vi.fn(),
    updateFlagState: vi.fn(),
    listSegments: vi.fn().mockResolvedValue({ data: [] }),
    getSegment: vi.fn(),
    createSegment: vi.fn(),
    updateSegment: vi.fn(),
    deleteSegment: vi.fn(),
    listAPIKeys: vi.fn().mockResolvedValue({ data: [] }),
    createAPIKey: vi.fn(),
    revokeAPIKey: vi.fn(),
    listAudit: vi.fn().mockResolvedValue({ data: [], total: 0 }),
    listMembers: vi.fn().mockResolvedValue({ data: [] }),
    inviteMember: vi.fn(),
    updateMemberRole: vi.fn(),
    removeMember: vi.fn(),
    getMemberPermissions: vi.fn().mockResolvedValue({ data: [] }),
    updateMemberPermissions: vi.fn(),
    listApprovals: vi.fn().mockResolvedValue({ data: [] }),
    getApproval: vi.fn(),
    createApproval: vi.fn(),
    reviewApproval: vi.fn(),
    killFlag: vi.fn(),
    promoteFlag: vi.fn(),
    compareEnvironments: vi.fn(),
    syncEnvironments: vi.fn(),
    inspectEntity: vi.fn(),
    compareEntities: vi.fn(),
    getFlagInsights: vi.fn().mockResolvedValue([]),
    getEvalMetrics: vi.fn().mockResolvedValue({ total_evaluations: 0, counters: [] }),
    resetEvalMetrics: vi.fn(),
    listWebhooks: vi.fn().mockResolvedValue({ data: [] }),
    createWebhook: vi.fn(),
    updateWebhook: vi.fn(),
    deleteWebhook: vi.fn(),
    listWebhookDeliveries: vi.fn().mockResolvedValue({ data: [] }),
    createCheckout: vi.fn(),
    getSubscription: vi.fn(),
    getUsage: vi.fn(),
    getOnboarding: vi.fn(),
    updateOnboarding: vi.fn(),
    exchangeToken: vi.fn(),
  };
}
