apiVersion: v2
name: featuresignals
description: FeatureSignals - Open Source Feature Flag Platform
type: application
version: 1.0.0
appVersion: "0.1.0"
keywords:
  - feature-flags
  - feature-management
  - feature-signals
home: https://featuresignals.com
sources:
  - https://github.com/featuresignals/featuresignals
maintainers:
  - name: FeatureSignals Team
    email: engineering@featuresignals.com
    url: https://featuresignals.com
icon: https://featuresignals.com/favicon.ico
kubeVersion: ">=1.28.0-0"
dependencies:
  - name: postgresql
    version: "~15.5.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
    alias: postgresql
