package domain

// AISuggestion is a predictive or autonomous suggestion generated by the
// AI layer for a feature on the Console. Suggestions are surfaced at
// decision points (Layer 2: Predictive) or trigger autonomous actions
// (Layer 3: Autonomous).
type AISuggestion struct {
	FlagKey     string  `json:"flag_key"`
	Type        string  `json:"type"`        // "cleanup" | "rollback_risk" | "advance_ready" | "health_warning" | "dependency_conflict"
	Priority    string  `json:"priority"`    // "info" | "warning" | "critical"
	Message     string  `json:"message"`     // Human-readable, feature-level language
	Action      string  `json:"action"`      // "Create cleanup PR" | "Review rollout config" | "Advance to next stage" | "Check Monitor stage"
	AutoFixable bool    `json:"auto_fixable"`
	Confidence  float64 `json:"confidence"`  // 0.0-1.0
}

// AISuggestionType represents the well-known suggestion type constants.
const (
	AITypeCleanup            = "cleanup"
	AITypeRollbackRisk       = "rollback_risk"
	AITypeAdvanceReady       = "advance_ready"
	AITypeHealthWarning      = "health_warning"
	AITypeDependencyConflict = "dependency_conflict"
)

// AIPriority represents the well-known priority constants.
const (
	AIPriorityInfo     = "info"
	AIPriorityWarning  = "warning"
	AIPriorityCritical = "critical"
)

// priorityOrder returns a numeric ordering for priorities (higher = more urgent).
func priorityOrder(p string) int {
	switch p {
	case AIPriorityCritical:
		return 3
	case AIPriorityWarning:
		return 2
	case AIPriorityInfo:
		return 1
	default:
		return 0
	}
}

// HighestPriority returns the suggestion with the highest priority from a slice.
// If the slice is empty, it returns nil. Ties are broken by higher confidence.
func HighestPriority(suggestions []AISuggestion) *AISuggestion {
	if len(suggestions) == 0 {
		return nil
	}
	best := &suggestions[0]
	for i := 1; i < len(suggestions); i++ {
		s := &suggestions[i]
		if priorityOrder(s.Priority) > priorityOrder(best.Priority) ||
			(priorityOrder(s.Priority) == priorityOrder(best.Priority) && s.Confidence > best.Confidence) {
			best = s
		}
	}
	return best
}
