// Package domain defines the core business interfaces for FeatureSignals.
//
// EventBus is the port for asynchronous messaging between services.
// It abstracts the message broker (NATS JetStream, Kafka, Redis Streams, etc.)
// so that business logic never depends on a specific messaging transport.
package domain

import (
	"context"
	"errors"
	"time"
)

// ErrEventBusClosed is returned when operations are attempted on a closed bus.
var ErrEventBusClosed = errors.New("event bus: closed")

// ─── Message envelope ─────────────────────────────────────────────────────

// EventEnvelope is the standard message wrapper for all events flowing
// through the EventBus. Every message carries tracing context, a unique
// ID for idempotency, and a typed payload.
type EventEnvelope struct {
	// ID is a unique identifier for this message, used for idempotent
	// processing. Generated by the publisher.
	ID string `json:"id"`

	// Subject is the topic/channel this message was published on.
	// Follows the naming convention: {domain}.{entity}.{action}
	// Examples: "eval.flag.toggled", "billing.meter.updated", "agent.action.completed"
	Subject string `json:"subject"`

	// Timestamp is when the message was published.
	Timestamp time.Time `json:"timestamp"`

	// CorrelationID links related messages (e.g., a request and its response).
	CorrelationID string `json:"correlation_id,omitempty"`

	// CausationID is the ID of the message that caused this one.
	CausationID string `json:"causation_id,omitempty"`

	// TraceID carries the OpenTelemetry trace context for distributed tracing.
	TraceID string `json:"trace_id,omitempty"`

	// SpanID carries the OpenTelemetry span context.
	SpanID string `json:"span_id,omitempty"`

	// TenantID is the organization ID for multi-tenant routing and isolation.
	TenantID string `json:"tenant_id,omitempty"`

	// ContentType describes the payload encoding (e.g., "application/json").
	ContentType string `json:"content_type,omitempty"`

	// Payload is the message body. Interpretation depends on ContentType.
	Payload []byte `json:"payload"`
}

// ─── EventSubscription handle ──────────────────────────────────────────────

// EventSubscription represents an active subscription to an EventBus subject.
// Call Unsubscribe to stop receiving messages.
type EventSubscription interface {
	// Unsubscribe stops the subscription. After Unsubscribe, no further
	// messages are delivered. Unsubscribe is idempotent.
	Unsubscribe() error
}

// ─── EventBus interface ───────────────────────────────────────────────────

// EventBus provides asynchronous publish/subscribe messaging between
// services. Implementations must be safe for concurrent use.
//
// Topic naming convention:
//
//	{domain}.{entity}.{action}
//	Examples: eval.flag.toggled, billing.meter.updated, agent.action.completed
//
// Consumer groups are identified by a durable name. Messages are delivered
// to exactly one consumer in the group (competing consumers pattern).
//
// A nil/no-op implementation is valid for single-instance deployments
// where cross-service messaging is unnecessary.
type EventBus interface {
	// Publish sends a message to the given subject. The message is
	// delivered to all subscribers of that subject. Returns ErrEventBusClosed
	// if the bus has been shut down.
	Publish(ctx context.Context, env *EventEnvelope) error

	// Subscribe registers a handler for messages on the given subject.
	// Messages are delivered asynchronously; the handler should be
	// safe for concurrent use. The returned Subscription can be used
	// to unsubscribe.
	//
	// If consumerGroup is non-empty, messages are load-balanced across
	// all subscribers in the same consumer group (competing consumers).
	// If empty, every subscriber receives every message (fan-out).
	Subscribe(ctx context.Context, subject string, consumerGroup string, handler EventHandler) (EventSubscription, error)

	// Request publishes a message and waits for a single response.
	// This implements the request/reply pattern. timeout bounds the
	// wait. Returns the response envelope or an error if the timeout
	// is exceeded or the bus is closed.
	Request(ctx context.Context, env *EventEnvelope, timeout time.Duration) (*EventEnvelope, error)

	// Close shuts down the event bus. Active subscriptions are
	// terminated. Publish and Subscribe return ErrEventBusClosed
	// after Close. Close is idempotent.
	Close() error
}

// EventHandler is the callback invoked when a message is received on a
// subscription. The handler receives the message envelope and must not
// retain references to the envelope or payload after returning.
//
// Return an error to signal that the message could not be processed.
// The EventBus implementation decides whether to redeliver (at-least-once)
// or discard (at-most-once) based on its configuration.
type EventHandler func(ctx context.Context, env *EventEnvelope) error
