import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Integration Guide',
      collapsed: false,
      items: [
        'getting-started/quickstart',
        'getting-started/installation',
        'getting-started/create-your-first-flag',
        {
          type: 'category',
          label: 'Core Concepts',
          items: [
            'core-concepts/feature-flags',
            'core-concepts/toggle-categories',
            'core-concepts/implementation-patterns',
            'core-concepts/projects-and-environments',
            'core-concepts/targeting-and-segments',
            'core-concepts/percentage-rollouts',
            'core-concepts/ab-experimentation',
            'core-concepts/mutual-exclusion',
            'core-concepts/prerequisites',
            'core-concepts/flag-lifecycle',
          ],
        },
        {
          type: 'category',
          label: 'Advanced',
          items: [
            'advanced/relay-proxy',
            'advanced/scheduling',
            'advanced/kill-switch',
            'advanced/approval-workflows',
            'advanced/webhooks',
            'advanced/audit-logging',
            'advanced/rbac',
          ],
        },
        {
          type: 'category',
          label: 'Architecture',
          items: [
            'architecture/overview',
            'architecture/evaluation-engine',
            'architecture/real-time-updates',
          ],
        },
        {
          type: 'category',
          label: 'Deployment',
          items: [
            'self-hosting/onboarding-guide',
            'deployment/docker-compose',
            'deployment/self-hosting',
            'deployment/on-premises',
            'deployment/configuration',
            'operations/incident-runbook',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/feature-flag-checkout',
        'tutorials/ab-testing-react',
        'tutorials/progressive-rollout',
        'tutorials/kill-switch',
      ],
    },
    {
      type: 'category',
      label: 'Flag Engine',
      items: [
        'dashboard/overview',
        'dashboard/managing-flags',
        'dashboard/evaluation-metrics',
        'dashboard/flag-health',
        'dashboard/env-comparison',
        'dashboard/entity-inspector',
        'dashboard/entity-comparison',
        'dashboard/usage-insights',
      ],
    },
  ],
  api: [
    'api-reference/overview',
    'api-reference/authentication',
    'api-reference/projects',
    'api-reference/environments',
    'api-reference/flags',
    'api-reference/flag-state',
    'api-reference/evaluation',
    'api-reference/segments',
    'api-reference/api-keys',
    'api-reference/team-management',
    'api-reference/approvals',
    'api-reference/webhooks',
    'api-reference/audit-log',
    'api-reference/metrics',
    'api-reference/billing',
    'api-reference/demo',
    'api-reference/onboarding',
    {
      type: 'category',
      label: 'Enterprise',
      items: [
        'api-reference/sso',
        'api-reference/scim',
        'api-reference/mfa',
        'api-reference/ip-allowlist',
        'api-reference/custom-roles',
        'api-reference/data-export',
      ],
    },
  ],
  sdks: [
    'sdks/overview',
    'sdks/go',
    'sdks/nodejs',
    'sdks/python',
    'sdks/java',
    'sdks/dotnet',
    'sdks/ruby',
    'sdks/react',
    'sdks/vue',
    'sdks/openfeature',
  ],
  compliance: [
    'compliance/security-overview',
    {
      type: 'category',
      label: 'GDPR',
      items: [
        'compliance/privacy-policy',
        'compliance/data-retention',
        'compliance/dpa-template',
        'compliance/subprocessors',
        'compliance/gdpr-rights',
      ],
    },
    {
      type: 'category',
      label: 'SOC 2',
      items: [
        'compliance/soc2/controls-matrix',
        'compliance/soc2/evidence-collection',
        'compliance/soc2/incident-response',
      ],
    },
    'compliance/ccpa-cpra',
    'compliance/iso27701/pims-overview',
    'compliance/data-privacy-framework',
    'compliance/iso27001/isms-overview',
    'compliance/hipaa',
    'compliance/dora',
    'compliance/csa-star',
  ],
};

export default sidebars;
